services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            XDEBUG_MODE: '${XDEBUG_MODE:-debug}'
        volumes:
            - '../../:/var/www/html'
        networks:
            - dev
        depends_on:
            pgsql:
                condition: service_healthy
            redis:
                condition: service_healthy
    pgsql:
        image: 'postgres:18-alpine'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'dev-pgsql:/var/lib/postgresql'
            - '../pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - dev
        healthcheck:
            test: ['CMD', 'pg_isready', '-q', '-d', '${DB_DATABASE}', '-U', '${DB_USERNAME}']
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'dev-redis:/data'
        networks:
            - dev
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            retries: 3
            timeout: 5s
networks:
    dev:
        driver: bridge
volumes:
    dev-pgsql:
        driver: local
    dev-redis:
        driver: local
