name: Execute Pint Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.4]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          docker run --rm \
            -v $(pwd):/var/www/html \
            -w /var/www/html \
            php:8.4-cli \
            bash -c "apt-get update && apt-get install -y unzip git libpng-dev libjpeg-dev libfreetype6-dev && \
                     curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
                     composer install --ignore-platform-reqs"

      - name: Install Pint
        run: |
          docker run --rm \
            -v $(pwd):/var/www/html \
            -w /var/www/html \
            php:8.4-cli \
            bash -c "composer global require laravel/pint"

      - name: Run Pint
        run: |
          docker run --rm \
            -v $(pwd):/var/www/html \
            -w /var/www/html \
            php:8.4-cli \
            bash -c "pint --test"

      - name: Stop and clean up containers
        if: always()
        run: |
          docker container prune -f
          docker volume prune -f
          docker network prune -f
