name: Run Laravel Tests

on: [push, pull_request]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.4]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Install dependencies
        run: |
          docker run --rm \
            -v $(pwd):/var/www/html \
            -w /var/www/html \
            laravelsail/php82-composer:latest \
            composer install --ignore-platform-reqs

      - name: Start Sail
        run: |
          cp .env.example .env
          ./vendor/bin/sail up -d

      - name: Run migrations
        run: |
          ./vendor/bin/sail artisan migrate --force

      - name: Run tests
        run: |
          ./vendor/bin/sail test

      - name: Stop Sail
        if: always()
        run: ./vendor/bin/sail down
