name: Execute tests

on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.4]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          docker run --rm \
            -v $(pwd):/var/www/html \
            -w /var/www/html \
            php:8.2-cli \
            bash -c "apt-get update && apt-get install -y unzip git libpq-dev && \
                     docker-php-ext-install pdo_pgsql pgsql && \
                     curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
                     composer install --ignore-platform-reqs"

      - name: Start PostgreSQL container
        run: |
          docker run --name postgres -e POSTGRES_PASSWORD=root -e POSTGRES_DB=make_my_test -d postgres:13

      - name: Wait for PostgreSQL to be ready
        run: |
          until docker exec postgres pg_isready -U root; do
            echo "Waiting for PostgreSQL to be ready...";
            sleep 1;
          done

      - name: Run migrations
        run: |
          docker run --rm \
            --link postgres:postgres \
            -v $(pwd):/var/www/html \
            -w /var/www/html \
            php:8.2-cli \
            bash -c "cp .env.example .env && \
                     sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=pgsql/' .env && \
                     sed -i 's/DB_HOST=127.0.0.1/DB_HOST=postgres/' .env && \
                     sed -i 's/DB_PASSWORD=/DB_PASSWORD=root/' .env && \
                     php artisan migrate --force"

      - name: Run tests
        run: |
          docker run --rm \
            --link postgres:postgres \
            -v $(pwd):/var/www/html \
            -w /var/www/html \
            php:8.2-cli \
            bash -c "./vendor/bin/phpunit"

      - name: Stop and clean up containers
        if: always()
        run: |
          docker stop postgres || true
          docker rm postgres || true
          docker container prune -f
          docker volume prune -f
          docker network prune -f
